<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMiKSzXm\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMiKSzXm/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerMiKSzXm.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerMiKSzXm\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerMiKSzXm\appAppKernelProdContainer([
    'container.build_hash' => 'MiKSzXm',
    'container.build_id' => '3c7429f2',
    'container.build_time' => 1709239327,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMiKSzXm');
