<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWbVvxnT\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWbVvxnT/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerWbVvxnT.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerWbVvxnT\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerWbVvxnT\appAppKernelProdContainer([
    'container.build_hash' => 'WbVvxnT',
    'container.build_id' => '4bf549f5',
    'container.build_time' => 1709238970,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWbVvxnT');
