version: '3'
services:
  web:
    build: apache
    volumes:
      - ./app:/app
      - ./apache/certificados:/certificados
      - ./apache/configuracion.conf:/etc/apache2/sites-enabled/configuracion.conf
    ports:
      - 8012:80
      - 443:443
    env_file:
      - ./apache/prod_conf/.env.prod
