version: '3'
services:
  web:
    build: apache
    volumes:
      - ./app:/app
      - ./apache/certificados:/certificados
      - ./apache/configuracion.conf:/etc/apache2/sites-enabled/configuracion.conf
    ports:
      - 8012:80
      - 443:443
  basedatos:
    image: mysql:latest
    env_file:
      - ./apache/dev_conf/.env.dev
    volumes:
      - ./database/backup:/docker-entrypoint-initdb.b
      - ./database/backup:/database/backup
      - datos:/var/lib/mysql
volumes:
  datos:
