<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQC1DbiI\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQC1DbiI/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerQC1DbiI.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerQC1DbiI\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerQC1DbiI\appAppKernelProdContainer([
    'container.build_hash' => 'QC1DbiI',
    'container.build_id' => '36759b26',
    'container.build_time' => 1709505159,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQC1DbiI');
