<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIeeeVWC\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIeeeVWC/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerIeeeVWC.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerIeeeVWC\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerIeeeVWC\appAppKernelProdContainer([
    'container.build_hash' => 'IeeeVWC',
    'container.build_id' => '43caeda0',
    'container.build_time' => 1709505583,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIeeeVWC');
